### ISSUE TITLE
Add support for index files

### ISSUE THREAD

**Issue by GrimLink** [wkillerud/vscode-scss#16]
In Sass you can also import files without needing to specify the index file.

https://sass-lang.com/documentation/at-rules/use#index-files

Currently this extension does not support imports using this and requires you specify the full path.
It would be awesome if this also added 😉

| Works | Does not |
| ------ | --------- |
| ![Screenshot 2022-08-09 at 12 14 32](https://user-images.githubusercontent.com/4387541/183627077-2e1f6520-fd06-4f48-9a68-464491586453.jpg) |  ![Screenshot 2022-08-09 at 12 14 49](https://user-images.githubusercontent.com/4387541/183627101-3257434c-fc36-40c7-aeab-5c0445287465.jpg) |

**Comment by wkillerud** [comment]
That's odd, I'll look into it. I mostly use index files for forwards, but of course suggestions should also include things declared in the file itself.

**Comment by wkillerud** [comment]
I uploaded `2.6.1` to the Marketplace, and it should be live now @GrimLink. 

It doesn't fix `Cmd/Ctrl+Click` on the path, but the rest _should_ work. The issue is in a dependency, so I'll try to ask for help about that link navigation. Hopefully that'll get fixed at some point soon as well.

Thank you so much for the bug report!
